import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Head, useForm } from '@inertiajs/react';
import { FileUp, Trash2 } from 'lucide-react';
import { ChangeEvent, FormEvent, useState } from 'react';
import { z } from 'zod';

const fileSchema = z.instanceof(File).refine((file) => ['application/pdf', 'image/jpeg', 'image/png'].includes(file.type), 'Only PDF, JPG, and PNG files are allowed.').refine((file) => file.size <= 10 * 1024 * 1024, 'Each file must be 10 MB or smaller.');
export default function Upload({ shop, limits }: { shop: { name: string; upload_url: string }; limits: { max_files: number; max_file_size_mb: number } }) {
 const { data, setData, post, processing, errors } = useForm({ documents: [] as File[] }); const [error, setError] = useState<string | null>(null);
 const choose = (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); const next = [...data.documents, ...files]; if (next.length > limits.max_files) return setError(`Upload up to ${limits.max_files} files.`); for (const file of files) { const result = fileSchema.safeParse(file); if (!result.success) return setError(result.error.issues[0].message); } setError(null); setData('documents', next); };
 const submit = (event: FormEvent) => { event.preventDefault(); post(shop.upload_url, { forceFormData: true }); };
 return <><Head title={`Upload | ${shop.name}`} /><main className="bg-muted/30 min-h-screen p-4"><div className="mx-auto max-w-lg space-y-4"><h1 className="text-xl font-semibold">Upload documents</h1><p className="text-muted-foreground text-sm">{shop.name} · PDF, JPG, PNG · up to {limits.max_files} files</p><Card><CardHeader><CardTitle className="text-base">Choose files</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><label className="border-primary/40 flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed p-4 text-center"><FileUp className="text-primary mb-2" /><span className="font-medium">Tap to select files</span><span className="text-muted-foreground mt-1 text-xs">Maximum {limits.max_file_size_mb} MB each</span><input className="sr-only" type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={choose} /></label>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{errors.documents && <Alert variant="destructive"><AlertDescription>{errors.documents}</AlertDescription></Alert>}<div className="space-y-2">{data.documents.map((file, index) => <div key={`${file.name}-${index}`} className="flex items-center justify-between rounded-md border p-3 text-sm"><span className="truncate">{file.name} <small className="text-muted-foreground">({(file.size / 1024 / 1024).toFixed(1)} MB)</small></span><Button type="button" variant="ghost" size="icon" aria-label={`Remove ${file.name}`} onClick={() => setData('documents', data.documents.filter((_, item) => item !== index))}><Trash2 /></Button></div>)}</div><Button className="w-full" disabled={processing || data.documents.length === 0}>{processing ? 'Uploading…' : 'Continue to configuration'}</Button></form></CardContent></Card></div></main></>;
}
